main/routes/web.php
<?php

use App\Models\Category;
use App\Models\Product;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();


Route::get('/', function () {
    return view('welcome');
})->name('dashboard');

Route::get('/auth/redirect/{provider}', 'Admin\SocialController@redirect');
Route::get('/callback/{provider}', 'Admin\SocialController@callback');

Route::group(['namespace' => 'frontend'], function(){
    Route::group(['prefix' => '/products', 'as' => 'products.'], function () {
        Route::get('/cart', 'ProductController@viewCart')->name('cart');
        Route::get('/checkout', 'ProductController@checkout')->name('checkout');
        Route::get('/add-product', 'ProductController@create')->name('create');
        Route::get('/{make}/models', 'ProductController@modelOptions');
        Route::get('/search', 'ProductController@search')->name('search');
        Route::get('/{product}', 'ProductController@show')->name('show');
        Route::get('add-to-cart/{product}', 'ProductController@addToCart')->name('add.cart');
        Route::get('update-cart/{product}', 'ProductController@updateCart')->name('update.cart');
        Route::get('remove-cart/{product}', 'ProductController@removeCart')->name('remove.cart');
        Route::post('place-order', 'ProductController@placeOrder')->name('place-order');
    });

    Route::group(['prefix' => '/sub-categories', 'as' => 'sub-category.'], function(){
       Route::get('/{subCategory}', 'SubCategoryController@show')->name('show');
    });

    Route::get('/track-my-order', 'PagesController@trackMyOrder');
    Route::get('/my-account', 'PagesController@myAccount');
    Route::get('/return-policy', 'PagesController@returnPolicy');
    Route::get('/faqs', 'PagesController@faqs');
    Route::get('/about-us', 'PagesController@aboutUs');
    Route::get('/contact-us', 'PagesController@contactUs');
    Route::post('send/contact-us/email', 'PagesController@sendContactUsEmail')->name('contact-us.email');
    Route::get('/feedback', 'PagesController@feedback');
    Route::get('/terms-and-conditions', 'PagesController@termsAndConditions');
    Route::get('/privacy-policy', 'PagesController@privacyPolicy');
    Route::get('/thank-you','ProductController@thankyou')->name('thankyou');
});



//admin routes
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin'], 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        Route::get('/', 'CategoryController@index')->name('index');
        Route::post('/', 'CategoryController@store')->name('store');
        Route::get('/{category}/edit', 'CategoryController@edit')->name('edit');
        Route::post('/{category}', 'CategoryController@update')->name('update');
        Route::get('/{category}/delete', 'CategoryController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'sub-categories', 'as' => 'sub-categories.'], function () {
        Route::get('/', 'SubCategoryController@index')->name('index');
        Route::post('/', 'SubCategoryController@store')->name('store');
        Route::get('/{subCategory}/edit', 'SubCategoryController@edit')->name('edit');
        Route::post('/{subCategory}', 'SubCategoryController@update')->name('update');
        Route::get('/{subCategory}/delete', 'SubCategoryController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'makes', 'as' => 'makes.'], function () {
        Route::get('/', 'MakeController@index')->name('index');
        Route::post('/', 'MakeController@store')->name('store');
        Route::get('/{make}/edit', 'MakeController@edit')->name('edit');
        Route::post('/{make}', 'MakeController@update')->name('update');
        Route::get('/{make}/delete', 'MakeController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'models', 'as' => 'models.'], function () {
        Route::get('/', 'MakeModelController@index')->name('index');
        Route::post('/', 'MakeModelController@store')->name('store');
        Route::get('/{model}/edit', 'MakeModelController@edit')->name('edit');
        Route::post('/{model}', 'MakeModelController@update')->name('update');
        Route::get('/{model}/delete', 'MakeModelController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::post('/', 'ProductController@store')->name('store');
        Route::get('/{product}/edit', 'ProductController@edit')->name('edit');
        Route::post('/{product}', 'ProductController@update')->name('update');
        Route::get('/{product}/delete', 'ProductController@destroy')->name('destroy');
        Route::get('/sub-categories/options', 'ProductController@subCategoryOptions')->name('sub-categories');
        Route::get('/models/options', 'ProductController@modelsOptions');
    });

    Route::group(['prefix' => 'orders', 'as' => 'orders.'], function () {
        Route::get('/', 'OrderController@index')->name('index');
        Route::get('/{order}', 'OrderController@show')->name('show');
        Route::get('/{order}/{status}', 'OrderController@updateStatus')->name('status');
    });

});


Route::get('/home', function () {
    if (isAdministratorUser()) {
        return redirect()->route('admin.dashboard');
    } else {
        return redirect()->route('dashboard');
    }
});

Route::get('/migrate', function () {

    echo '<br>init migrate:install...';
    Artisan::call('migrate');
    echo 'done migrate:install';

});

Route::get('/migrate/{key}', function ($key) {

    echo '<br>init migrate:' . $key . '...';
    Artisan::call('migrate:' . $key);
    echo 'done migrate:' . $key;

});

Route::get('/db-seed', function () {
    try {
        echo '<br>init db:seed...';
        Artisan::call('db:seed');
        echo 'done db:seed';

    } catch (Exception $e) {
        return $e->getMessage();
    }

});

Route::get('/import', function (){
   $products = Product::all();
   foreach ($products as $product){
       if($product->category_id){
           $product->categories()->sync($product->category_id);
       }
       if($product->sub_category_id){
           $product->subCategories()->sync($product->sub_category_id);
       }
       if($product->make_id){
           $product->makes()->sync($product->make_id);
       }
       if($product->make_model_id){
           $product->makeModels()->sync($product->make_model_id);
       }
   }
   return 'imported successfully!';
});


Route::get('add/sku/', function (){
    $products = Product::all();
    foreach ($products as $product){
        $product->update(['sku' => substr(md5(microtime()), 0, 6)]);
    }
});

main/app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Make;
use App\Models\MakeModel;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\ProductYear;
use App\Models\SubCategory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductController extends Controller
{

    private $rules;


    public function index()
    {
        $products = Product::query()->with(Product::$ALL_RELATIONS)->get();
        $categories = Category::all();
        $subCategories = SubCategory::all();
        $makes = Make::all();
        $models = MakeModel::all();
        return view('admin.products.index', compact('products', 'categories', 'subCategories', 'makes', 'models'));
    }


    public function store(Request $request)
    {
        $this->validateRequest($request);

        $video_url = null;
        if ($request->filled('video_url')) {
            $video_url = $this->getYoutubeEmbedUrl($request->video_url);
        }
        DB::beginTransaction();
        try {
            $product = Product::query()->create([
                'name' => $request->name,
                'sku' => substr(md5(microtime()), 0, 6),
                'slug' => Str::slug($request->name),
                'price' => $request->price,
                'discount_price' => $request->filled('discount_price') ? $request->discount_price : $request->price,
//                'make_id' => $request->filled('make_id') ? $request->make_id : null,
//                'make_model_id' => $request->filled('make_model_id') ? $request->make_model_id : null,
                'description' => $request->filled('description') ? $request->description : null,
                'qty' => $request->filled('qty') ? $request->qty : null,
                'color' => $request->filled('color') ? $request->color : null,
                'size' => $request->filled('size') ? $request->size : null,
                'vendor' => $request->filled('vendor') ? $request->vendor : null,
                'video_url' => $video_url,
                'shipping_charges' => $request->filled('shipping_charges') ? $request->shipping_charges : 0.00,
                'is_free_shipping' => $request->filled('is_free_shipping') ? true : false,
                'is_available' => (boolean)$request->is_avaliable
                ]);

            $product->categories()->sync($request->category_ids);
            $product->subCategories()->sync($request->sub_category_ids);
            $product->makes()->sync($request->make_ids);
            $product->makeModels()->sync($request->make_model_ids);

            if ($request->filled('years')) {
                foreach ($request->years as $year) {
                    ProductYear::query()->create([
                        'product_id' => $product->id,
                        'year' => $year
                    ]);
                }
            }


            $this->saveImages($request, $product);
            DB::commit();
            session()->flash('success', 'Added Successfully!');
            return redirect()->route('admin.products.index');
        } catch (\Exception $exception) {
            DB::rollBack();
            session()->flash('error', $exception->getMessage());
            return back()->withInput($request->all());
        }

    }


    public function edit(Product $product)
    {
        $categories = Category::all();
        $subCategories = SubCategory::all();
        $makes = Make::all();
        $models = MakeModel::all();
        $productYears = $product->years()->pluck('year')->toArray();
        return view('admin.products.edit', compact('product', 'categories', 'subCategories', 'makes', 'models', 'productYears'));
    }


    public function update(Request $request, Product $product)
    {
        $this->validateRequest($request, $product->id);
        $video_url = null;
        if ($request->filled('video_url')) {
            $video_url = $this->getYoutubeEmbedUrl($request->video_url);
        }
        DB::beginTransaction();
        try {
            $product->update([
                'name' => $request->name,
                'slug' => Str::slug($request->name),
//                'category_id' => $request->category_id,
//                'sub_category_id' => $request->sub_category_id,
//                'make_id' => $request->filled('make_id') ? $request->make_id : null,
//                'make_model_id' => $request->filled('make_model_id') ? $request->make_model_id : null,
                'description' => $request->filled('description') ? $request->description : null,
                'price' => $request->price,
                'discount_price' => $request->filled('discount_price') ? $request->discount_price : $request->price,
                'qty' => $request->filled('qty') ? $request->qty : null,
                'color' => $request->filled('color') ? $request->color : null,
                'size' => $request->filled('size') ? $request->size : null,
                'vendor' => $request->filled('vendor') ? $request->vendor : null,
                'video_url' => $video_url,
                'shipping_charges' => $request->filled('shipping_charges') ? $request->shipping_charges : 0.00,
                'is_free_shipping' => $request->filled('is_free_shipping') ? true : false,
                'is_available' => (boolean)$request->is_avaliable
            ]);

            $product->categories()->sync($request->category_ids);
            $product->subCategories()->sync($request->sub_category_ids);
            $product->makes()->sync($request->make_ids);
            $product->makeModels()->sync($request->make_model_ids);

            ProductYear::query()->where('product_id', $product->id)->delete();

            if ($request->filled('years')) {
                foreach ($request->years as $year) {
                    ProductYear::query()->create([
                        'product_id' => $product->id,
                        'year' => $year
                    ]);
                }
            }

            $this->saveImages($request, $product);

            DB::commit();
            session()->flash('success', 'Updated Successfully!');
            return redirect()->route('admin.products.index');
        } catch (\Exception $exception) {
            DB::rollBack();
            session()->flash('error', $exception->getMessage());
            return back()->withInput($request->all());
        }

    }


    public function destroy(Product $product)
    {
        DB::beginTransaction();
        try {
            $product->delete();
            DB::commit();
            session()->flash('success', 'Deleted Successfully!');
            return redirect()->route('admin.products.index');
        } catch (\Exception $e) {
            DB::rollBack();
            session()->flash('error', 'Something Went Wrong!');
            return back();
        }
    }

    /**
     * @param Request $request
     * @param $product
     * @throws \Illuminate\Validation\ValidationException
     */
    public function saveImages(Request $request, $product)
    {
        if ($request->hasFile('images')) {
            // $product->images()->delete();
            $this->validate($request, [
                'images.*' => 'sometimes|required|image|mimes:jpeg,png,jpg,gif,svg|max:5120'
            ]);
            foreach ($request->images as $image) {
                ProductImage::query()->create([
                    'product_id' => $product->id,
                    'image' => storeImage($image, 'products'),
                ]);
            }
        }
        if ($request->hasFile('img')) {
            $this->validate($request, [
                'img' => 'sometimes|required|image|mimes:jpeg,png,jpg,gif,svg|max:5120'
            ]);
            $product->img = storeImage($request->file('img'), 'products');
            $product->save();
        }
    }

    /**
     * @param Category $category
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function subCategoryOptions()
    {
        $subCategories = SubCategory::query()->whereIn('category_id', \request()->ids)->get();
        return view('admin.products.partials.sub-categories', compact('subCategories'));
    }

    /**
     * @param Make $make
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function modelsOptions()
    {
        $models = MakeModel::query()->whereIn('make_id', \request()->ids)->get();
        return view('admin.products.partials.models', compact('models'));
    }

    function getYoutubeEmbedUrl($url)
    {
        $shortUrlRegex = '/youtu.be\/([a-zA-Z0-9_-]+)\??/i';
        $longUrlRegex = '/youtube.com\/((?:embed)|(?:watch))((?:\?v\=)|(?:\/))([a-zA-Z0-9_-]+)/i';

        if (preg_match($longUrlRegex, $url, $matches)) {
            $youtube_id = $matches[count($matches) - 1];
        }

        if (preg_match($shortUrlRegex, $url, $matches)) {
            $youtube_id = $matches[count($matches) - 1];
        }
        return 'https://www.youtube.com/embed/' . $youtube_id;
    }

    private function validateRequest(Request $request, $product_id = null){
        $rule = $product_id ? ',' . $product_id : '';
        unset($request['sku']);
        $rules = [
            'name' => 'required|min:2|max:64',
            'category_ids' => 'required|array',
            'sub_category_ids' => 'required|array',
            'price' => 'required|numeric',
            'discount_price' => 'nullable|numeric',
            'shipping_charges' => 'nullable|numeric'
        ];
        $this->validate($request, $rules);
    }
}

main/resources/views/admin/products/edit.blade.php
<form method="POST" action="{{route('admin.products.update', $product->id)}}" enctype="multipart/form-data">

    {{ csrf_field() }}
    <div class="modal-body" id="edit-body">
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="name">Name <sup>*</sup></label>
                    <input id="name" type="text" class="form-control" name="name"
                           value="{{$product->name}}" required>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="category">Category <sup>*</sup></label>
                    <select multiple id="category" class="form-control select2 category" name="category_ids[]" required>
                        <option value="">Select</option>
                        @foreach($categories as $category)
                            <option
                                value="{{$category->id}}" {{ count($product->categories) && in_array($category->id , $product->categories()->pluck('categories.id')->toArray()) ? 'selected' : ''}}>{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="sub-category">Sub Category <sup>*</sup></label>
                    <select multiple id="sub-category" class="form-control select2 sub-category" name="sub_category_ids[]" required>
                        <option value="">Select</option>
                        @foreach($subCategories as $subCategory)
                            <option
                                value="{{$subCategory->id}}"
                                {{ count($product->subCategories) && in_array($subCategory->id , @$product->subCategories()->pluck('sub_categories.id')->toArray()) ? 'selected' : ''}}>{{ $subCategory->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="price">Price <sup>*</sup></label>
                    <input id="price" type="text" class="form-control" name="price"
                           value="{{$product->price}}" required>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="discount-price">Discount Price </label>
                    <input id="discount-price" type="text" class="form-control"
                           name="discount_price" value="{{$product->discount_price}}">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="qty">Qty</label>
                    <input id="qty" type="number" min="0" class="form-control" name="qty"
                           value="{{$product->qty}}">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="make">Make</label>
                    <select id="make" class="form-control select2 make" name="make_ids[]" multiple>
                        <option value="">Select</option>
                        @foreach($makes as $make)
                            <option
                                value="{{$make->id}}" {{ count($product->makes) && in_array($make->id, $product->makes()->pluck('makes.id')->toArray()) ? 'selected' : ''}}>{{ $make->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="model">Model</label>
                    <select id="model" class="form-control select2 model" name="make_model_ids[]" multiple>
                        <option value="">Select</option>
                        @foreach($models as $model)
                            <option
                                value="{{ $model->id }}" {{count($product->makeModels) && in_array($model->id, $product->makeModels()->pluck('make_models.id')->toArray()) ? 'selected' : ''}}>{{ $model->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="year">Year</label>
                    <select id="year" class="form-control select2" name="years[]" multiple>
                        <option value="">Select</option>
                        @foreach(getYears() as $year)
                            <option
                                value="{{$year}}" {{count($productYears) && in_array($year, $productYears) ? 'selected' : ''}}>{{$year}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>

        {{--        <div class="row">--}}
        {{--            <div class="col-sm-4">--}}
        {{--                <div class="form-group">--}}
        {{--                    <label for="color">Color</label>--}}
        {{--                    <input id="color" type="text" name="color" class="form-control"--}}
        {{--                           value="{{$product->color}}">--}}
        {{--                </div>--}}
        {{--            </div>--}}
        {{--            <div class="col-sm-4">--}}
        {{--                <div class="form-group">--}}
        {{--                    <label for="size">Size</label>--}}
        {{--                    <input id="size" type="text" name="size" class="form-control"--}}
        {{--                           value="{{$product->size}}">--}}
        {{--                </div>--}}
        {{--            </div>--}}
        {{--        </div>--}}

        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="size">Size</label>
                    <select class="form-control select2" name="size" id="size">
                        <option value="">Select</option>
                        <option value="x-small" {{$product->size == 'x-small' ? 'selected' : '' }}>X-Small</option>
                        <option value="small" {{ $product->size == 'small' ? 'selected' : '' }}>Small</option>
                        <option value="medium" {{ $product->size == 'medium' ? 'selected' : '' }}>Medium</option>
                        <option value="large" {{ $product->size == 'large' ? 'selected' : '' }}>Large</option>
                        <option value="x-large" {{ $product->size == 'x-large' ? 'selected' : '' }}>X-Large</option>
                    </select>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="vendor">Vendor</label>
                    <input type="text" name="vendor" id="vendor" class="form-control" value="{{ $product->vendor }}">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="video_url">Video URL</label>
                    <input type="text" name="video_url" id="video_url" class="form-control" value="{{ $product->video_url }}">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="shipping_charges">Shipping Charges</label>
                    <input type="text" name="shipping_charges" id="shipping_charges" class="form-control" value="{{$product->shipping_charges}}">
                </div>
            </div>

            <div class="col-sm-4">
                <div class="form-group">
                    <label for="sku">SKU Code</label>
                    <input type="text" name="sku" id="sku" class="form-control" value="{{$product->sku}}" disabled>
                </div>
            </div>

            <div class="col-sm-4">
                <div class="form-group">
                    <label for="is_avaliable">Stock Status</label>
                    <select id="is_avaliable" class="form-control select2 is_avaliable" name="is_avaliable">
                        <option value="1" {{$product->is_available ? 'selected' : ''}}>Available Stock</option>
                        <option value="0" {{!$product->is_available ? 'selected' : ''}}>Out of Stock</option>
                    </select>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea id="description" name="description"
                              class="form-control wysiwyg">{!! $product->description  !!}</textarea>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="is_free_shipping">Is Free Shipping ?</label>
                    <input type="checkbox" name="is_free_shipping" id="is_free_shipping"
                           class="checkbox checkbox-primary"
                           value="1"
                           {{ $product->is_free_shipping ? 'checked' : '' }}
                    >
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="custom-file">
                    <input type="file" class="custom-file-input" name="img" id="customFile">
                    <label class="custom-file-label"  for="customFile">Choose Timeline image</label>
                </div>
            </div>
        </div>
        <div class="row">
            
            <div class="col-sm-12">
            Images
                <div class="input-images-2"></div>
            </div>
            

                @if($product->img)
                    <div class="col-12">
                        <h2>Timeline Image</h2>
                        <img
                            src="{{asset('main/storage/app/public/'.$product->img)}}"
                            id="profile-img-tag" class="img-profile" alt="not found" style="height: 200px;width:100%">
                    </div>
                @endif

        </div>
    </div>

    <!-- Modal footer -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>

</form>
<script>
$(document).ready(function(){
    let preloaded = [
            @foreach($product->images as $image)
    {id: {{ $loop->index }}, src: "{{asset('main/storage/app/public/'.$image->image)}}"},
    @endforeach
];

$('.input-images-2').imageUploader({
    preloaded: preloaded,
    imagesInputName: 'images',
    preloadedInputName: 'old'
});
});
</script>