main/routes/web.php
<?php

use App\Models\Category;
use App\Models\Product;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();


Route::get('/', function () {
    return view('welcome');
})->name('dashboard');

Route::get('/auth/redirect/{provider}', 'Admin\SocialController@redirect');
Route::get('/callback/{provider}', 'Admin\SocialController@callback');

Route::group(['namespace' => 'frontend'], function(){
    Route::group(['prefix' => '/products', 'as' => 'products.'], function () {
        Route::get('/cart', 'ProductController@viewCart')->name('cart');
        Route::get('/checkout', 'ProductController@checkout')->name('checkout');
        Route::get('/add-product', 'ProductController@create')->name('create');
        Route::get('/{make}/models', 'ProductController@modelOptions');
        Route::get('/search', 'ProductController@search')->name('search');
        Route::get('/{product}', 'ProductController@show')->name('show');
        Route::get('add-to-cart/{product}', 'ProductController@addToCart')->name('add.cart');
        Route::get('update-cart/{product}', 'ProductController@updateCart')->name('update.cart');
        Route::get('remove-cart/{product}', 'ProductController@removeCart')->name('remove.cart');
        Route::post('place-order', 'ProductController@placeOrder')->name('place-order');
    });

    Route::group(['prefix' => '/sub-categories', 'as' => 'sub-category.'], function(){
       Route::get('/{subCategory}', 'SubCategoryController@show')->name('show');
    });

    Route::get('/track-my-order', 'PagesController@trackMyOrder');
    Route::get('/my-account', 'PagesController@myAccount');
    Route::get('/return-policy', 'PagesController@returnPolicy');
    Route::get('/faqs', 'PagesController@faqs');
    Route::get('/about-us', 'PagesController@aboutUs');
    Route::get('/contact-us', 'PagesController@contactUs');
    Route::post('send/contact-us/email', 'PagesController@sendContactUsEmail')->name('contact-us.email');
    Route::get('/feedback', 'PagesController@feedback');
    Route::get('/terms-and-conditions', 'PagesController@termsAndConditions');
    Route::get('/privacy-policy', 'PagesController@privacyPolicy');
    Route::get('/thank-you','ProductController@thankyou')->name('thankyou');
});



//admin routes
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin'], 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        Route::get('/', 'CategoryController@index')->name('index');
        Route::post('/', 'CategoryController@store')->name('store');
        Route::get('/{category}/edit', 'CategoryController@edit')->name('edit');
        Route::post('/{category}', 'CategoryController@update')->name('update');
        Route::get('/{category}/delete', 'CategoryController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'sub-categories', 'as' => 'sub-categories.'], function () {
        Route::get('/', 'SubCategoryController@index')->name('index');
        Route::post('/', 'SubCategoryController@store')->name('store');
        Route::get('/{subCategory}/edit', 'SubCategoryController@edit')->name('edit');
        Route::post('/{subCategory}', 'SubCategoryController@update')->name('update');
        Route::get('/{subCategory}/delete', 'SubCategoryController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'makes', 'as' => 'makes.'], function () {
        Route::get('/', 'MakeController@index')->name('index');
        Route::post('/', 'MakeController@store')->name('store');
        Route::get('/{make}/edit', 'MakeController@edit')->name('edit');
        Route::post('/{make}', 'MakeController@update')->name('update');
        Route::get('/{make}/delete', 'MakeController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'models', 'as' => 'models.'], function () {
        Route::get('/', 'MakeModelController@index')->name('index');
        Route::post('/', 'MakeModelController@store')->name('store');
        Route::get('/{model}/edit', 'MakeModelController@edit')->name('edit');
        Route::post('/{model}', 'MakeModelController@update')->name('update');
        Route::get('/{model}/delete', 'MakeModelController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::post('/', 'ProductController@store')->name('store');
        Route::get('/{product}/edit', 'ProductController@edit')->name('edit');
        Route::post('/{product}', 'ProductController@update')->name('update');
        Route::get('/{product}/delete', 'ProductController@destroy')->name('destroy');
        Route::get('/sub-categories/options', 'ProductController@subCategoryOptions')->name('sub-categories');
        Route::get('/models/options', 'ProductController@modelsOptions');
    });

    Route::group(['prefix' => 'orders', 'as' => 'orders.'], function () {
        Route::get('/', 'OrderController@index')->name('index');
        Route::get('/{order}', 'OrderController@show')->name('show');
        Route::get('/{order}/{status}', 'OrderController@updateStatus')->name('status');
    });

});


Route::get('/home', function () {
    if (isAdministratorUser()) {
        return redirect()->route('admin.dashboard');
    } else {
        return redirect()->route('dashboard');
    }
});

Route::get('/migrate', function () {

    echo '<br>init migrate:install...';
    Artisan::call('migrate');
    echo 'done migrate:install';

});

Route::get('/migrate/{key}', function ($key) {

    echo '<br>init migrate:' . $key . '...';
    Artisan::call('migrate:' . $key);
    echo 'done migrate:' . $key;

});

Route::get('/db-seed', function () {
    try {
        echo '<br>init db:seed...';
        Artisan::call('db:seed');
        echo 'done db:seed';

    } catch (Exception $e) {
        return $e->getMessage();
    }

});

Route::get('/import', function (){
   $products = Product::all();
   foreach ($products as $product){
       if($product->category_id){
           $product->categories()->sync($product->category_id);
       }
       if($product->sub_category_id){
           $product->subCategories()->sync($product->sub_category_id);
       }
       if($product->make_id){
           $product->makes()->sync($product->make_id);
       }
       if($product->make_model_id){
           $product->makeModels()->sync($product->make_model_id);
       }
   }
   return 'imported successfully!';
});


Route::get('add/sku/', function (){
    $products = Product::all();
    foreach ($products as $product){
        $product->update(['sku' => substr(md5(microtime()), 0, 6)]);
    }
});

main/app/Http/Controllers/frontend/PagesController.php
<?php

namespace App\Http\Controllers\frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Mockery\Exception;

class PagesController extends Controller
{
    public function trackMyOrder()
    {
        return view('frontend.pages.track-my-order');
    }

    public function myAccount()
    {
        return view('frontend.pages.my-account');
    }

    public function returnPolicy()
    {
        return view('frontend.pages.return-policy');
    }

    public function faqs()
    {
        return view('frontend.pages.faqs');
    }

    public function aboutUs()
    {
        return view('frontend.pages.about-us');
    }

    public function contactUs()
    {
        return view('frontend.pages.contact-us');
    }

    public function termsAndConditions()
    {
        return view('frontend.pages.terms-and-conditions');
    }

    public function privacyPolicy()
    {
        return view('frontend.pages.privacy-policy');
    }

    public function feedback()
    {
        return view('frontend.pages.feedback');
    }

    public function sendContactUsEmail(Request $request)
    {

        $this->validate($request, [
            'email' => 'required|email',
            'subject' => 'required|min:3',
            'body' => 'required|min:6',
            'attach_file' => 'mimes:jpeg,png,jpg,gif,svg,txt,pdf,doc,docx,ppt,xls'
        ]);

        $data = array(
            'name' => $request->name,
            'email' => $request->email,
            'subject' => $request->subject,
            'bodyMessage' => $request->body,
            'attach_file' => $request->attach_file,
        );
        try {
            $body = "<h3>You have new contact From Contact Form</h3><div>$request->body</div><p>Sent Via $request->email</p>";

            if ($request->file('attach_file')) {
                Mail::send([], [], function ($message) use ($data, $body) {
                    $message->to('muhammadtalha353@gmail.com')
                        ->subject($data['subject'])
                        ->from($data['email'])
                        ->attach($data['attach_file']->getRealPath(), array(
                            'as' => 'attachment.' . $data['attach_file']->getClientOriginalExtension(),
                            'mime' => $data['attach_file']->getMimeType()
                        ))->setBody($body, 'text/html');
                });

            } else {
                Mail::send([], [], function ($message) use ($data, $body) {
                    $message->to('info@megamotorsports.pk')
                        ->subject($data['subject'])
                        ->from($data['email'])
                        ->setBody($body, 'text/html');
                });
            }

            return back()->with('success', 'Email has been sent successfully!');
        } catch (Exception $e) {
            return back()->with('error', $e->getMessage());
        }

    }
}

main/app/Http/Controllers/frontend/ProductController.php
<?php

namespace App\Http\Controllers\frontend;

use App\Cart;
use App\Http\Controllers\Controller;
use App\Models\Make;
use App\Models\Order;
use App\Models\OrderProduct;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Mockery\Exception;

class ProductController extends Controller
{
    public function create()
    {
        return view('frontend.productadd');
    }

    public function show(Product $product)
    {
        return view('frontend.products.show', compact('product'));
    }

    public function search()
    {
        $make_id = \request()->filled('make_id') ? request()->make_id : null;
        $model_id = \request()->filled('model_id') ? \request()->model_id : null;
        $year = \request()->filled('year') ? request()->year : null;
        $keyword = \request()->filled('keyword') ? request()->keyword : null;

        if (!is_null($keyword)) {
            $data = Product::query()->with(Product::$ALL_RELATIONS)
                ->where('name', 'like', '%' . $keyword . '%')
                ->get()
                ->groupBy('categories.*.name');

            if(count($data) == 0){
                $searchWords = explode(' ', $keyword);
                $data = Product::query()->with(Product::$ALL_RELATIONS);
                foreach($searchWords as $word){
                    $data->orWhere('name', 'LIKE', '%'.$word.'%');
                }
                $data = $data->distinct()->get();
                $data = $data->groupBy('categories.*.name');    
            }
        } else {
            $data = Product::query()->with(Product::$ALL_RELATIONS)
                ->when($make_id, function ($query) use ($make_id) {
                    $query->whereHas('makes', function ($q) use ($make_id) {
                        $q->where('makes.id', $make_id);
                    });
                })
                ->when($model_id, function ($query) use ($model_id) {
                    $query->whereHas('makeModels', function ($q) use ($model_id) {
                        $q->where('make_models.id', $model_id);
                    });
                })->when($year, function ($query) use ($year) {
                    $query->whereHas('years', function ($q) use ($year) {
                        $q->where('year', $year);
                    });
                })
                ->get()
                ->groupBy('categories.*.name');
        }

        return view('frontend.search', compact('data', 'make_id', 'model_id', 'year'));
    }

    public function modelOptions(Make $make)
    {
        return view('frontend.partials.model-options', compact('make'));
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function viewCart()
    {
        return view('frontend.products.cart');
    }

    public function checkout()
    {
//        if(Auth::user()){
            return view('frontend.products.checkout');
//        }
//        return redirect('/login');
    }

    public function addToCart(Product $product, Request $request)
    {
        $oldCart = Session::has('cart') ? Session::get('cart') : null;
        $cart = new Cart($oldCart);
        $qty = $request->qty ? $request->qty : 1;
        $cart->addProduct($product, $qty);
        Session::put('cart', $cart);
        return back()->with('success', 'Product <b>' . $product->name . '</b> has been added successfully!');
    }

    public function updateCart(Product $product, Request $request)
    {
        $oldCart = Session::has('cart') ? Session::get('cart') : null;
        $cart = new Cart($oldCart);
        $cart->updateProduct($product, $request->qty);
        Session::put('cart', $cart);
        return back()->with('success', 'Product <b>' . $product->name . '</b> has been successfully Updated in the Cart');
    }

    public function removeCart(Product $product)
    {
        $oldCart = Session::has('cart') ? Session::get('cart') : null;
        $cart = new Cart($oldCart);
        $cart->removeProduct($product);
        Session::put('cart', $cart);
        return back()->with('success', 'Product <b>' . $product->name . '</b> has been successfully removed From the Cart');
    }

    public function placeOrder(Request $request)
    {
        $rules = [
            'first_name' => 'required|min:3',
            'phone' => 'required',
            'email' => 'sometimes|email',
            'address' => 'required'
        ];
        $this->validate($request, $rules);
        if (Session::has('cart')) {
            $cart = session()->get('cart');
            $total = $cart->getTotalPrice();
            if($cart->getTotalPrice() < 1000){
                $total = $total + 200;
            }
            try {
                $order = Order::query()->create([
                    'user_id' => auth()->user() ? auth()->user()->id : null,
                    'first_name' => $request->first_name,
                    'last_name' => $request->last_name,
                    'email' => $request->email,
                    'phone' => $request->phone,
                    'address' => $request->address,
                    'city' => $request->city,
                    'province' => $request->province,
                    'zip' => $request->zip,
                    'total' => $total,
                ]);
                //insert into order_product table
                foreach ($cart->getContents() as $data) {
                    OrderProduct::query()->create([
                        'order_id' => $order->id,
                        'product_id' => $data['product']->id,
                        'quantity' => $data['qty'],
                    ]);
                }
            } catch (Exception $e) {
                return back()->with('warning', 'Something went wrong!');
            }
        } else {
            return back()->with('warning', 'Your cart is empty');
        }

        Session::forget('cart');
        return redirect('/thank-you');
    }

    public function thankyou()
    {
        return view('frontend.thankyou');
    }

}

main/app/Http/Controllers/frontend/SubCategoryController.php
<?php

namespace App\Http\Controllers\frontend;

use App\Http\Controllers\Controller;
use App\Models\MakeModel;
use App\Models\SubCategory;
use Illuminate\Http\Request;

class SubCategoryController extends Controller
{
    public function show(SubCategory $subCategory)
    {
        $models = MakeModel::query()->limit(10)->groupBy('make_id')->get();
        return view('frontend.sub-categories.show', compact('subCategory', 'models'));
    }
}

main/resources/views/frontend/partials/header.blade.php
<header class="head_header">
    <nav class="head-stores-h">
        <div class="wrap">
            <ul class="head-stores js-head-stores" style="overflow: hidden">
            <li><a class="imgwhitelogo" href="/"><img src="/images/logo-white.png" alt="" width="60" height="30"></a></li>
                @foreach(\App\Models\SubCategory::query()->latest()->limit(6)->get() as $subCategory)

                    {{--                <li>--}}
                    {{--                    <div class="item head-stores-icon -active -i1-15">Car &amp; Truck</div>--}}
                    {{--                </li>--}}
                    <li><a href="{{ route('sub-category.show', $subCategory->id) }}"
                           class="item head-stores-icon -i5-0 js-new-tab">{{ $subCategory->name }}</a></li>
                @endforeach
            </ul>
            <script class="js-header-stores-template" type="text/x-handlebars-template">
                <div class="head-stores-dd">
                    <ul class="items">
                        <li><span data-hlk="#" class="item head-stores-icon -i1-31 js-new-tab">Semi Truck</span>
                        </li>
                        <li><span data-hlk="#"
                                  class="item head-stores-icon -i1-6 -hot js-store-link-block js-new-tab">Motorcycle</span>
                        </li>
                        <li><span data-hlk="#" class="item head-stores-icon -i1-20 js-new-tab">Powersports</span>
                        </li>
                        <li><span data-hlk="#" class="item head-stores-icon -i3-0 js-new-tab">RV / Camper</span>
                        </li>
                        <li><span data-hlk="#" class="item head-stores-icon -i4-0 js-new-tab">Boating</span></li>
                        <li><span data-hlk="#" class="item head-stores-icon -i2-0 js-new-tab">Recreation</span></li>
                        <li><span data-hlk="#" class="item head-stores-icon -i5-0 js-new-tab">Tools</span></li>
                    </ul>
                </div>
            </script>
        </div>
    </nav>
    <div style="z-index: 1200;">

        <nav id="sidenav" style="overflow: hidden;">
            <ul>
                <li><a href="/">Home</a></li>
                {{--                    <li class="active"><a href="javascript:void(0)" style="text-align: center; font-weight: bold;">Departments</a>--}}
                {{--                    </li>--}}
                @foreach($allCategories as $category)
                    <li><span> <img
                                src="{{$category->img ? asset('main/storage/app/public/'.$category->img) :'/admin/img/no-photo.png'}}"
                                class="img-icon"> {{ $category->name }}</span>
                        <ul>
                            @foreach($category->childrens as $subCategory)
                                <li><a href="{{route('sub-category.show', $subCategory->id)}}"><img
                                            src="{{$subCategory->image ? asset('main/storage/app/public/'.$subCategory->image) :'/admin/img/no-photo.png'}}"
                                            class="img-icon">{{ $subCategory->name }}</a>
                                </li>
                            @endforeach
                        </ul>
                    </li>
                @endforeach

                <li></li>
                <li><a href="/login" style="text-align: center; font-weight: bold;">Login / Register</a></li>
                <li><a href="/products/search" style="text-align: center; font-weight: bold;">Search</a></li>
                {{--                    <li><a href="{{route('products.create')}}" style="text-align: center; font-weight: bold;">Add--}}
                {{--                            Product</a></li>--}}
            </ul>
        </nav>
	 <nav id="cartmenu" style="overflow: hidden;">
                    <ul>
                        <li class="text-center"><h4 style="padding: 10px; font-size: 16px !important; margin: auto;">Shopping Cart</h4></li>
                        <li>
                                    
                            <table style="width: 100%;">
		@if(session()->has('cart'))
		@foreach(session()->get('cart')->getContents() as $key => $data)
<form method="GET" action="{{ route('products.update.cart', $data['product']->id) }}">
<tr>
                                <td style="width: 20%; padding: 7px;"><img src="{{ $data['product']->images()->first() ? asset('main/storage/app/public/'.$data['product']->images()->first()->image) :'/admin/img/no-photo.png'}}" width="60" height="60"></td>
                                <td style="text-align: left;"><p style="line-height: 20px; padding-top: 5px;">{{ $data['product']->name }}</p></td>
                                <td style="line-height: 55px; width: 10%;"><a href="{{ route('products.remove.cart', $data['product']->id) }}" style="padding: 8px;"><i class="fas fa-times"></i></a></td>
                                </tr>
 </form>
           		@endforeach
		@endif
                                
                            </table>                                    
                        
                    </li>
                        

                    </ul>
                </nav>
    </div>
    <div class="header-top">

        <div class="wrap">
            <a class="head_logo_a -carid -dnone" href="/">MEGA MOTORS</a>
            <span><a class="left-menu-icon mburger" href="#sidenav">
                        <b></b>
                        <b></b>
                        <b></b>
                    </a></span>
            @if(session()->has('cart'))
                <div class="row custom-cart float-right">
	<style>
	.cart-iconnn
{
font-size: 20px !important;
}
@media only screen and (max-width: 744px) {
  .cart-iconnn {
    margin-top: 11px !important;
  }
}

</style>
                    <a href="#cartmenu" id="cart" class="cart-iconnn" style=" color:var(--red-color);"><i class="fas fa-cart-arrow-down"></i><span
                            class="badge">{{ session('cart')->getTotalQty() }}</span></a>
                </div>
            @endif
            {{--            <ul class="nav-tool-wrap">--}}

            {{--                <li class="header-dd-hover-element -with-padding js-garage-header-menu" aria-haspopup="true">--}}
            {{--                    <div class="nav-tool -garage -arrow">--}}
            {{--                        <span class="js-nav-tool-title -txt -arrow -without-content">Garage</span>--}}
            {{--                        <span class="icon -icon-garage"><span--}}
            {{--                                class="count-item -type-1 js-my-garage-counter"></span>--}}
            {{--                            </span>--}}
            {{--                        <div class="header-garage-subtitle js-header-garage-mmy"></div>--}}
            {{--                    </div>--}}
            {{--                    <div class="mygarage-dd header-dd-h">--}}
            {{--                        <div class="head-dd-loader js-my-garage-dd-loader"></div>--}}
            {{--                        <div class="js-my-garage-dd-content" data-vehicle-garage-id="15"></div>--}}
            {{--                    </div>--}}
            {{--                </li>--}}

            {{--            </ul>--}}

            <div class="header-account header-dd-hover-element js-account-header-menu">
                <div class="nav-tool">
                    <span class="js-nav-tool-title -txt -arrow">
                        @if(auth()->user())
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                               data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                        {{ auth()->user()->name }}
                    </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
<a class="dropdown-item" href="{{ route('logout') }}"
   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>                    </div>
                        @else
                            <a href="/login" class="link">Login / Register</a>
                        @endif
                    </span>

                </div>
                <div class="header-account-dd header-dd-h js-account-dd-holder">
                    <div class="head-dd-loader"></div>
                </div>
            </div>
            <label class="header-search-btn js-search-btn" data-toggle-class="search-show">
                <form action="{{url('/products/search')}}" method="GET">
                    <input class="search-form-field" name="keyword" type="text"
                           style="position: absolute; margin-top: -39px; width: 91%;" placeholder="Search....">
                    <button type="submit" class="search-form-button"><i class="fas fa-search srch-btn"></i></button>
                </form>
            </label>
        </div>
    </div>
    <nav class="head-dd-h">
        <div class="wrap">
            <div class="head-dd-help-center">
                <div
                    class="help-center-nav-btn -arrow -arrow-red header-dd-hover-element js-help-center-header-menu"
                    aria-haspopup="true">
                    {{--                    <span>Help Center</span>--}}
                    {{--                    <div class="header-help-center-dd header-dd-h js-help-center-dd-holder">--}}
                    {{--                        <div class="head-dd-loader"></div>--}}
                    {{--                    </div>--}}
                </div>
            </div>
            <ul class="head-dd js-head-depts">
                <li class="it js-head-dept" data-id="407" data-vehicle-id="15" data-store-id="0">
                    <span class="head-dd-main"><a class="link" href="/">Home</a></span>
                </li>
                @foreach(\App\Models\SubCategory::query()->limit(8)->get() as $subCategory)
                    <li class="it js-head-dept" data-id="407" data-vehicle-id="15" data-store-id="0">
                        <span class="head-dd-main"><a class="link"
                                                      href="{{route('sub-category.show', $subCategory->id)}}">{{ $subCategory->name }}</a></span>
                    </li>
                @endforeach

            </ul>
        </div>
    </nav>
    <div class="head-dd-cont-holder js-head-dd-cont-holder">
        <div class="wrap">
            <div class="head-dd-cont-holder-close js-head-dd-cont-holder-close"></div>
        </div>
    </div>
</header>

main/resources/views/frontend/partials/model-options.blade.php
<option value="" disabled selected>2 &nbsp;&nbsp;|&nbsp;&nbsp; MODEL
@foreach($make->makeModels as $model)
    <option value="{{ $model->id }}">{{ $model->name }}</option>
@endforeach