main/routes/web.php
<?php

use App\Models\Category;
use App\Models\Product;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();


Route::get('/', function () {
    return view('welcome');
})->name('dashboard');

Route::get('/auth/redirect/{provider}', 'Admin\SocialController@redirect');
Route::get('/callback/{provider}', 'Admin\SocialController@callback');

Route::group(['namespace' => 'frontend'], function(){
    Route::group(['prefix' => '/products', 'as' => 'products.'], function () {
        Route::get('/cart', 'ProductController@viewCart')->name('cart');
        Route::get('/checkout', 'ProductController@checkout')->name('checkout');
        Route::get('/add-product', 'ProductController@create')->name('create');
        Route::get('/{make}/models', 'ProductController@modelOptions');
        Route::get('/search', 'ProductController@search')->name('search');
        Route::get('/{product}', 'ProductController@show')->name('show');
        Route::get('add-to-cart/{product}', 'ProductController@addToCart')->name('add.cart');
        Route::get('update-cart/{product}', 'ProductController@updateCart')->name('update.cart');
        Route::get('remove-cart/{product}', 'ProductController@removeCart')->name('remove.cart');
        Route::post('place-order', 'ProductController@placeOrder')->name('place-order');
    });

    Route::group(['prefix' => '/sub-categories', 'as' => 'sub-category.'], function(){
       Route::get('/{subCategory}', 'SubCategoryController@show')->name('show');
    });

    Route::get('/track-my-order', 'PagesController@trackMyOrder');
    Route::get('/my-account', 'PagesController@myAccount');
    Route::get('/return-policy', 'PagesController@returnPolicy');
    Route::get('/faqs', 'PagesController@faqs');
    Route::get('/about-us', 'PagesController@aboutUs');
    Route::get('/contact-us', 'PagesController@contactUs');
    Route::post('send/contact-us/email', 'PagesController@sendContactUsEmail')->name('contact-us.email');
    Route::get('/feedback', 'PagesController@feedback');
    Route::get('/terms-and-conditions', 'PagesController@termsAndConditions');
    Route::get('/privacy-policy', 'PagesController@privacyPolicy');
    Route::get('/thank-you','ProductController@thankyou')->name('thankyou');
});



//admin routes
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin'], 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        Route::get('/', 'CategoryController@index')->name('index');
        Route::post('/', 'CategoryController@store')->name('store');
        Route::get('/{category}/edit', 'CategoryController@edit')->name('edit');
        Route::post('/{category}', 'CategoryController@update')->name('update');
        Route::get('/{category}/delete', 'CategoryController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'sub-categories', 'as' => 'sub-categories.'], function () {
        Route::get('/', 'SubCategoryController@index')->name('index');
        Route::post('/', 'SubCategoryController@store')->name('store');
        Route::get('/{subCategory}/edit', 'SubCategoryController@edit')->name('edit');
        Route::post('/{subCategory}', 'SubCategoryController@update')->name('update');
        Route::get('/{subCategory}/delete', 'SubCategoryController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'makes', 'as' => 'makes.'], function () {
        Route::get('/', 'MakeController@index')->name('index');
        Route::post('/', 'MakeController@store')->name('store');
        Route::get('/{make}/edit', 'MakeController@edit')->name('edit');
        Route::post('/{make}', 'MakeController@update')->name('update');
        Route::get('/{make}/delete', 'MakeController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'models', 'as' => 'models.'], function () {
        Route::get('/', 'MakeModelController@index')->name('index');
        Route::post('/', 'MakeModelController@store')->name('store');
        Route::get('/{model}/edit', 'MakeModelController@edit')->name('edit');
        Route::post('/{model}', 'MakeModelController@update')->name('update');
        Route::get('/{model}/delete', 'MakeModelController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::post('/', 'ProductController@store')->name('store');
        Route::get('/{product}/edit', 'ProductController@edit')->name('edit');
        Route::post('/{product}', 'ProductController@update')->name('update');
        Route::get('/{product}/delete', 'ProductController@destroy')->name('destroy');
        Route::get('/sub-categories/options', 'ProductController@subCategoryOptions')->name('sub-categories');
        Route::get('/models/options', 'ProductController@modelsOptions');
    });

    Route::group(['prefix' => 'orders', 'as' => 'orders.'], function () {
        Route::get('/', 'OrderController@index')->name('index');
        Route::get('/{order}', 'OrderController@show')->name('show');
        Route::get('/{order}/{status}', 'OrderController@updateStatus')->name('status');
    });

});


Route::get('/home', function () {
    if (isAdministratorUser()) {
        return redirect()->route('admin.dashboard');
    } else {
        return redirect()->route('dashboard');
    }
});

Route::get('/migrate', function () {

    echo '<br>init migrate:install...';
    Artisan::call('migrate');
    echo 'done migrate:install';

});

Route::get('/migrate/{key}', function ($key) {

    echo '<br>init migrate:' . $key . '...';
    Artisan::call('migrate:' . $key);
    echo 'done migrate:' . $key;

});

Route::get('/db-seed', function () {
    try {
        echo '<br>init db:seed...';
        Artisan::call('db:seed');
        echo 'done db:seed';

    } catch (Exception $e) {
        return $e->getMessage();
    }

});

Route::get('/import', function (){
   $products = Product::all();
   foreach ($products as $product){
       if($product->category_id){
           $product->categories()->sync($product->category_id);
       }
       if($product->sub_category_id){
           $product->subCategories()->sync($product->sub_category_id);
       }
       if($product->make_id){
           $product->makes()->sync($product->make_id);
       }
       if($product->make_model_id){
           $product->makeModels()->sync($product->make_model_id);
       }
   }
   return 'imported successfully!';
});


Route::get('add/sku/', function (){
    $products = Product::all();
    foreach ($products as $product){
        $product->update(['sku' => substr(md5(microtime()), 0, 6)]);
    }
});

main/app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function childrens(){
        return $this->hasMany(SubCategory::class, 'category_id');
    }

    public function products(){
        return $this->belongsToMany(Product::class);
    }
}

main/app/Models/Make.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Make extends Model
{
   protected $guarded = [];

   public function makeModels(){
      return $this->hasMany(MakeModel::class);
   }
}

main/app/Models/MakeModel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class MakeModel extends Model
{
    protected $guarded = [];

    public function make()
    {
        return $this->belongsTo(Make::class);
    }
}

main/app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $guarded = [];
    protected $appends = ['full_name', 'status_label'];
    const STATUS_COMPLETED = 'completed';
    const STATUS_CANCELED = 'canceled';
    const STATUS_DELIVERED = 'delivered';
    const STATUS_PENDING = 'pending';

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function getStatusLabelAttribute()
    {
        if ($this->status == self::STATUS_PENDING) {
            return '<span class="badge badge-warning">' . ucfirst(self::STATUS_PENDING) . ' </span>';
        } elseif ($this->status == self::STATUS_DELIVERED) {
            return '<span class="badge badge-info">' . ucfirst(self::STATUS_DELIVERED) . ' </span>';
        } elseif ($this->status == self::STATUS_CANCELED) {
            return '<span class="badge badge-danger">' . ucfirst(self::STATUS_CANCELED) . ' </span>';
        } elseif ($this->status == self::STATUS_COMPLETED) {
            return '<span class="badge badge-success">' . ucfirst(self::STATUS_COMPLETED) . ' </span>';
        } else {
            return '<span class="badge badge-warning">' . ucfirst(self::STATUS_PENDING) . ' </span>';
        }
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function products()
    {
        return $this->belongsToMany(Product::class)->withPivot('quantity');
    }
}

main/app/Models/OrderProduct.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class OrderProduct extends Model
{
    protected $table = 'order_product';
    protected $guarded = [];
}

main/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $guarded = [];

    protected $appends = ['discount','total_price'];

    public static $ALL_RELATIONS = ['categories', 'subCategories', 'makes', 'makeModels'];

    /**
     * @return float|int
     */
    public function getDiscountAttribute()
    {
        return round((($this->price - $this->discount_price) / $this->price) * 100);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function years()
    {
        return $this->hasMany(ProductYear::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function images()
    {
        return $this->hasMany(ProductImage::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function makes()
    {
        return $this->belongsToMany(Make::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function makeModels()
    {
        return $this->belongsToMany(MakeModel::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function subCategories()
    {
        return $this->belongsToMany(SubCategory::class);
    }

    public function getTotalPriceAttribute()
    {
        if ($this->is_free_shipping) {
            return $this->discount_price;
        }
        return $this->discount_price + $this->shipping_charges;
    }

    public function getDiscountPriceAttribute($value){
        return round($value);
    }

    public function getPriceAttribute($value){
        return round($value);
    }

    public function getShippingChargesAttribute($value){
        return round($value);
    }
}

main/app/Models/ProductImage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProductImage extends Model
{
    protected $guarded = [];
}

main/app/Models/ProductYear.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProductYear extends Model
{
    protected $guarded = [];
}

main/app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = ['name', 'slug'];

    /**
     * @param $slug
     * @return |null
     * @throws \Exception
     */
    public static function findBySlug($slug)
    {
        $role = static::where('slug', $slug)->first();
        if ($role) {
            return $role;
        }

        throw new \Exception('role not found against ' . $slug . ' slug');
    }
}

main/app/Models/SubCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SubCategory extends Model
{
    protected $guarded = [];

    public function parent()
    {
        return $this->belongsTo(Category::class,'category_id');
    }

    public function products(){
        return $this->belongsToMany(Product::class);
    }
}

main/resources/views/admin/models/edit.blade.php
<form method="POST" action="{{route('admin.models.update', $model)}}">

    {{ csrf_field() }}

    <div class="modal-body" id="edit-body">
        <div class="form-group">
            <label for="name">Name <sup>*</sup></label>
            <input id="name" type="text" class="form-control" value="{{$model->name}}" name="name" required>
        </div>
        <div class="form-group">
            <label for="make_id">Make <sup>*</sup></label>
            <select id="make_id" class="form-control select2" name="make_id" required>
                <option value="">Select</option>
                @foreach($makes as $make)
                    <option value="{{$make->id}}" {{$make->id == @$model->make->id ? 'selected' : ''}}>{{ $make->name }}</option>
                @endforeach
            </select>
        </div>
    </div>


    <!-- Modal footer -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>

</form>

main/resources/views/admin/models/index.blade.php
@extends('admin.master')
@section('title') Dashboard @stop
@section('content')


    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Begin Breadcrumb -->
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-light">
                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Models</li>
            </ol>
        </nav>
        <!-- end Breadcrumb -->

        <!-- Page Heading -->

        <div class="card">
            <div class="card-body">

                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <div class="col-sm-8">
                        <h1 class="h3 mb-0 text-gray-800">Models</h1>
                    </div>
                    <div>
                        <a href="#add-model" class="btn btn-primary btn-sm" data-toggle="modal">Add model</a>
                    </div>
                </div>

                @include('shared.errors')

                <div class="table-responsive">
                    <table class="table table-hover table-sm" id="modeltable">
                        <thead>
                        <tr class="text-center">
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Make</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($models as $key => $model)
                            <tr class="text-center">
                                <th scope="row">{{ $key+1 }}</th>
                                <td>{{ $model->name }}</td>
                                <td>{{ @$model->make->name }}</td>
                                <td>
                                    <a href="Javascript:void(0)" data-id="{{$model->id}}" data-toggle="modal"
                                       class="btn btn-sm btn-success edit-model">edit</a>
                                    <a href="{{route('admin.models.destroy', $model->id)}}"
                                       class="btn btn-sm btn-danger">delete</a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <th colspan="5" class="text-center text-danger">Record Not Found!</th>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- The Modal -->
        <div class="modal fade" id="add-model">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Add model</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <form method="POST" action="{{route('admin.models.store')}}">

                        {{ csrf_field() }}

                        <div class="modal-body">
                            <div class="form-group">
                                <label for="name">Name <sup>*</sup></label>
                                <input id="name" type="text" class="form-control" name="name" required>
                            </div>
                            <div class="form-group">
                                <label for="make_id">Make <sup>*</sup></label>
                                <select id="make_id" class="form-control select2" name="make_id" required>
                                    <option value="">select</option>
                                    @foreach($makes as $make)
                                        <option value="{{$make->id}}" {{old('make_id') == $make->id ? 'selected' : ''}}>{{ $make->name }}</option>
                                        @endforeach
                                </select>
                            </div>
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">Save</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>

                    </form>

                </div>
            </div>
        </div>
        <div class="modal fade" id="edit-model-modal">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Edit model</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <div id="edit-body">

                    </div>

                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection
@section('scripts')
    <script>
        $('.edit-model').on('click', function (e) {
            let model_id = $(this).data('id');
            e.preventDefault();
            $.ajax({
                url: '/admin/models/' + model_id + '/edit',
                type: 'get',
                success: function (response) {
                    $('#edit-body').html(response);
                    $('#edit-model-modal').modal('show');
                }
            });
        })
    </script>
@endsection