main/routes/web.php
<?php

use App\Models\Category;
use App\Models\Product;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();


Route::get('/', function () {
    return view('welcome');
})->name('dashboard');

Route::get('/auth/redirect/{provider}', 'Admin\SocialController@redirect');
Route::get('/callback/{provider}', 'Admin\SocialController@callback');

Route::group(['namespace' => 'frontend'], function(){
    Route::group(['prefix' => '/products', 'as' => 'products.'], function () {
        Route::get('/cart', 'ProductController@viewCart')->name('cart');
        Route::get('/checkout', 'ProductController@checkout')->name('checkout');
        Route::get('/add-product', 'ProductController@create')->name('create');
        Route::get('/{make}/models', 'ProductController@modelOptions');
        Route::get('/search', 'ProductController@search')->name('search');
        Route::get('/{product}', 'ProductController@show')->name('show');
        Route::get('add-to-cart/{product}', 'ProductController@addToCart')->name('add.cart');
        Route::get('update-cart/{product}', 'ProductController@updateCart')->name('update.cart');
        Route::get('remove-cart/{product}', 'ProductController@removeCart')->name('remove.cart');
        Route::post('place-order', 'ProductController@placeOrder')->name('place-order');
    });

    Route::group(['prefix' => '/sub-categories', 'as' => 'sub-category.'], function(){
       Route::get('/{subCategory}', 'SubCategoryController@show')->name('show');
    });

    Route::get('/track-my-order', 'PagesController@trackMyOrder');
    Route::get('/my-account', 'PagesController@myAccount');
    Route::get('/return-policy', 'PagesController@returnPolicy');
    Route::get('/faqs', 'PagesController@faqs');
    Route::get('/about-us', 'PagesController@aboutUs');
    Route::get('/contact-us', 'PagesController@contactUs');
    Route::post('send/contact-us/email', 'PagesController@sendContactUsEmail')->name('contact-us.email');
    Route::get('/feedback', 'PagesController@feedback');
    Route::get('/terms-and-conditions', 'PagesController@termsAndConditions');
    Route::get('/privacy-policy', 'PagesController@privacyPolicy');
    Route::get('/thank-you','ProductController@thankyou')->name('thankyou');
});



//admin routes
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin'], 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        Route::get('/', 'CategoryController@index')->name('index');
        Route::post('/', 'CategoryController@store')->name('store');
        Route::get('/{category}/edit', 'CategoryController@edit')->name('edit');
        Route::post('/{category}', 'CategoryController@update')->name('update');
        Route::get('/{category}/delete', 'CategoryController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'sub-categories', 'as' => 'sub-categories.'], function () {
        Route::get('/', 'SubCategoryController@index')->name('index');
        Route::post('/', 'SubCategoryController@store')->name('store');
        Route::get('/{subCategory}/edit', 'SubCategoryController@edit')->name('edit');
        Route::post('/{subCategory}', 'SubCategoryController@update')->name('update');
        Route::get('/{subCategory}/delete', 'SubCategoryController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'makes', 'as' => 'makes.'], function () {
        Route::get('/', 'MakeController@index')->name('index');
        Route::post('/', 'MakeController@store')->name('store');
        Route::get('/{make}/edit', 'MakeController@edit')->name('edit');
        Route::post('/{make}', 'MakeController@update')->name('update');
        Route::get('/{make}/delete', 'MakeController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'models', 'as' => 'models.'], function () {
        Route::get('/', 'MakeModelController@index')->name('index');
        Route::post('/', 'MakeModelController@store')->name('store');
        Route::get('/{model}/edit', 'MakeModelController@edit')->name('edit');
        Route::post('/{model}', 'MakeModelController@update')->name('update');
        Route::get('/{model}/delete', 'MakeModelController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::post('/', 'ProductController@store')->name('store');
        Route::get('/{product}/edit', 'ProductController@edit')->name('edit');
        Route::post('/{product}', 'ProductController@update')->name('update');
        Route::get('/{product}/delete', 'ProductController@destroy')->name('destroy');
        Route::get('/sub-categories/options', 'ProductController@subCategoryOptions')->name('sub-categories');
        Route::get('/models/options', 'ProductController@modelsOptions');
    });

    Route::group(['prefix' => 'orders', 'as' => 'orders.'], function () {
        Route::get('/', 'OrderController@index')->name('index');
        Route::get('/{order}', 'OrderController@show')->name('show');
        Route::get('/{order}/{status}', 'OrderController@updateStatus')->name('status');
    });

});


Route::get('/home', function () {
    if (isAdministratorUser()) {
        return redirect()->route('admin.dashboard');
    } else {
        return redirect()->route('dashboard');
    }
});

Route::get('/migrate', function () {

    echo '<br>init migrate:install...';
    Artisan::call('migrate');
    echo 'done migrate:install';

});

Route::get('/migrate/{key}', function ($key) {

    echo '<br>init migrate:' . $key . '...';
    Artisan::call('migrate:' . $key);
    echo 'done migrate:' . $key;

});

Route::get('/db-seed', function () {
    try {
        echo '<br>init db:seed...';
        Artisan::call('db:seed');
        echo 'done db:seed';

    } catch (Exception $e) {
        return $e->getMessage();
    }

});

Route::get('/import', function (){
   $products = Product::all();
   foreach ($products as $product){
       if($product->category_id){
           $product->categories()->sync($product->category_id);
       }
       if($product->sub_category_id){
           $product->subCategories()->sync($product->sub_category_id);
       }
       if($product->make_id){
           $product->makes()->sync($product->make_id);
       }
       if($product->make_model_id){
           $product->makeModels()->sync($product->make_model_id);
       }
   }
   return 'imported successfully!';
});


Route::get('add/sku/', function (){
    $products = Product::all();
    foreach ($products as $product){
        $product->update(['sku' => substr(md5(microtime()), 0, 6)]);
    }
});

main/app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function childrens(){
        return $this->hasMany(SubCategory::class, 'category_id');
    }

    public function products(){
        return $this->belongsToMany(Product::class);
    }
}

main/app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $categories = Category::query()->get();
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $this->validate($request, ['name' => 'required|min:2|max:64']);
        DB::beginTransaction();
        try {
            $category = Category::query()->create([
                'slug' => Str::slug($request->name),
                'name' => $request->name,
            ]);
            $this->saveImage($request, $category);
            DB::commit();
            session()->flash('success', 'Added Successfully!');
            return redirect()->route('admin.categories.index');
        } catch (\Exception $exception) {
            DB::rollBack();
            session()->flash('error', 'Something went wrong!');
            return back()->withInput($request->all());
        }

    }

    /**
     * @param Category $category
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * @param Request $request
     * @param Category $category
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, Category $category)
    {
        $this->validate($request, ['name' => 'required|min:2|max:64']);
        DB::beginTransaction();
        try {
            $category->update([
                'slug' => Str::slug($request->name),
                'name' => $request->name,
            ]);
            $this->saveImage($request, $category);
            DB::commit();
            session()->flash('success', 'Updated Successfully!');
            return redirect()->route('admin.categories.index');
        } catch (\Exception $exception) {
            DB::rollBack();
            session()->flash('error', 'Something went wrong!');
            return back()->withInput($request->all());
        }

    }

    /**
     * @param Category $category
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Category $category)
    {
        DB::beginTransaction();
        try {
            $category->childrens()->delete();
            $category->delete();
            DB::commit();
            session()->flash('success', 'Deleted Successfully!');
            return redirect()->route('admin.categories.index');
        } catch (\Exception $e) {
            DB::rollBack();
            session()->flash('error', 'Something Went Wrong!');
            return back();
        }
    }

    /**
     * @param Request $request
     * @param $subCategory
     * @throws \Illuminate\Validation\ValidationException
     */
    public function saveImage(Request $request, $category)
    {
        if ($request->hasFile('img')) {
            $this->validate($request, [
                'img' => 'sometimes|required|image|mimes:jpeg,png,jpg,gif,svg|max:5120'
            ]);
            $category->img = storeImage($request->file('img'), 'categories');
        }
        $category->save();
    }
}

main/resources/views/admin/categories/edit.blade.php
<form method="POST" action="{{route('admin.categories.update', $category)}}" enctype="multipart/form-data">

    {{ csrf_field() }}

    <div class="modal-body" id="edit-body">
        <div class="form-group">
            <label for="name">Name <sup>*</sup></label>
            <input id="name" type="text" class="form-control" value="{{$category->name}}" name="name" required>
        </div>

        <div class="custom-file">
            <input type="file" class="custom-file-input" name="img" id="customFile">
            <label class="custom-file-label" for="customFile">Choose Image</label>
        </div>

        <div class="form-group mt-2">
            <img src="{{$category->img ? asset('main/storage/app/public/'.$category->img) :'/admin/img/no-photo.png'}}" id="profile-img-tag" class="img-profile" alt="not found" style="height: 200px;width:100%">
        </div>
    </div>
    <!-- Modal footer -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>

</form>

main/resources/views/admin/categories/index.blade.php
@extends('admin.master')
@section('title') Dashboard @stop
@section('content')


    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Begin Breadcrumb -->
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-light">
                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Categories</li>
            </ol>
        </nav>
        <!-- end Breadcrumb -->

        <!-- Page Heading -->

        <div class="card">
            <div class="card-body">

                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <div class="col-sm-8">
                        <h1 class="h3 mb-0 text-gray-800">Categories</h1>
                    </div>
                    <div>
                        <a href="#add-category" class="btn btn-primary btn-sm" data-toggle="modal">Add Category</a>
                    </div>
                </div>

                @include('shared.errors')

                <div class="table-responsive">
                    <table class="table table-hover table-sm" id="cattable">
                        <thead>
                        <tr class="text-center">
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">image</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($categories as $key => $category)
                            <tr class="text-center">
                                <th scope="row">{{ $key+1 }}</th>
                                <td>{{ $category->name }}</td>
                                <td>
                                    <img src="{{$category->img ? asset('main/storage/app/public/'.$category->img) :'/admin/img/no-photo.png'}}" id="profile-img-tag" class="img-profile" alt="not found" style="width: 50px">
                                </td>
                                <td>
                                    <a href="Javascript:void(0)" data-id="{{$category->id}}" data-toggle="modal" class="btn btn-sm btn-success edit-category">edit</a>
                                    <a href="{{route('admin.categories.destroy', $category->id)}}" class="btn btn-sm btn-danger">delete</a>
                                </td>
                            </tr>
                        @empty
                        <tr>
                            <th colspan="5" class="text-center text-danger">Record Not Found!</th>
                        </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- The Modal -->
        <div class="modal fade" id="add-category">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Add Category</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <form method="POST" action="{{route('admin.categories.store')}}" enctype="multipart/form-data">

                        {{ csrf_field() }}

                        <div class="modal-body">
                            <div class="form-group">
                                <label for="name">Name <sup>*</sup></label>
                                <input id="name" type="text" class="form-control" name="name" required>
                            </div>
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" name="img" id="customFile">
                                <label class="custom-file-label"  for="customFile">Choose Image</label>
                            </div>
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">Save</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>

                    </form>

                </div>
            </div>
        </div>
        <div class="modal fade" id="edit-category-modal">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Edit Category</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <div id="edit-body">

                    </div>

                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection
@section('scripts')
    <script>
        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function() {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
        
        $('.edit-category').on('click', function (e) {
            let category_id = $(this).data('id');
            e.preventDefault();
            $.ajax({
                url: '/admin/categories/' + category_id + '/edit',
                type: 'get',
                success: function (response) {
                    $('#edit-body').html(response);
                    $('#edit-category-modal').modal('show');
                    $(".custom-file-input").on("change", function() {
                        var fileName = $(this).val().split("\\").pop();
                        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
                    });
                }
            });
        })
    </script>
@endsection